name: spring-data-jpa
description: Plugin que gera a configuração necessária para aplicar o spring data jpa
display-name: spring-data-jpa
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
types:
  - app
inputs:
  - label: String para definir login de acesso. Pode usar os placeholders suportados pela configuração
    type: text
    name: login        
  - label: String para definir a senha de aceso
    type: text
    name: senha    
  - label: String jdbc de conexão com o banco de dados
    type: text
    name: string_jdbc
  - label: Escolha o tipo de banco de dados para adicionarmos a dependência
    type: text
    name: driver    
    items:
      - MySQL
      - PostgreSQL
  - label: Digite o nome do arquivo de configuração para que possa ser sugerido a configuração do banco. Ex - application.yml
    type: text
    name: arquivo_configuracao    
    default: "application.yml"

hooks:
  - type: edit
    trigger: after-render
    path: pom.xml          
    condition:
      variable: driver
      operator: ==
      value: MySQL                
    changes:
      - search:
          string: </dependencies>
          insert-before:
            snippet: snippets/mysql.xml
          when:
            not-exists-snippet: snippets/mysql.xml

  - type: edit
    trigger: after-render
    path: pom.xml          
    condition:
      variable: driver
      operator: ==
      value: PostgreSQL                
    changes:
      - search:
          string: </dependencies>
          insert-before:
            snippet: snippets/pg.xml
          when:
            not-exists-snippet: snippets/pg.xml            

  - type: edit
    trigger: after-render
    path: "src/main/resources/{{inputs.arquivo_configuracao}}"
    condition:
      variable: arquivo_configuracao
      operator: containsAny
      value: yml                            
    changes:
      - insert:
          line: -1
          snippet: snippets/conf-db.yml
  - type: edit
    trigger: after-render
    path: "src/main/resources/{{inputs.arquivo_configuracao}}"
    condition:
      variable: arquivo_configuracao
      operator: containsAny
      value: yaml                            
    changes:
      - insert:
          line: -1
          snippet: snippets/conf-db.yml
